prometheus:
  service:
    type: LoadBalancer
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        demo-spark: streaming
    serviceMonitorNamespaceSelector: {}
    podMonitorSelector:
      matchLabels:
        type: spark-operator
    podMonitorNamespaceSelector: {}
alertmanager:
  service:
    type: LoadBalancer
grafana:
  service:
    type: LoadBalancer
