apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "spark-demo"
  namespace: spark
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "damianfilonowicz/spark:azure"
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/application/streaming.py"
  sparkVersion: "3.2.1"
  sparkConf:
    "spark.ui.prometheus.enabled": "true"
    "spark.sql.shuffle.partitions": "4"
  restartPolicy:
    type: Never
    onFailureRetries: 1
    onFailureRetryInterval: 30
    onSubmissionFailureRetries: 1
    onSubmissionFailureRetryInterval: 30
  driver:
    cores: 1
    memory: "512m"
    serviceAccount: spark-sa
  executor:
    cores: 1
    instances: 1
    memory: "512m"
